### ISSUE TITLE
Run ended on an exception

### ISSUE THREAD

**Issue by jasikpark** [celinekurpershoek/link-checker#11]
https://github.com/jasikpark/jasik-xyz/runs/1073175123?check_suite_focus=true

```log
 /usr/bin/docker run --name b3ac606420a76c0f54fc1963b7689f4fab8f5_562df9 --label 3b3ac6 --workdir /github/workspace --rm -e INPUT_URL -e INPUT_HONORROBOTEXCLUSIONS -e INPUT_IGNOREPATTERNS -e INPUT_RECURSIVELINKS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/jasik-xyz/jasik-xyz":"/github/workspace" 3b3ac6:06420a76c0f54fc1963b7689f4fab8f5  "https://jasik.xyz" "false" "github,google" "true"
/usr/bin/blc -> /usr/lib/node_modules/broken-link-checker/bin/blc
/usr/bin/broken-link-checker -> /usr/lib/node_modules/broken-link-checker/bin/blc
+ broken-link-checker@0.7.8
added 102 packages from 131 contributors in 4.272s
=== BROKEN LINK CHECKER ===
Running broken link checker on url:  https://jasik.xyz 
Configuration: 
 Honor robot exclusions: false, 
 Exclude urls that match: github,google, 
 Resursive urls: true
/usr/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:159
  err.response = response;
               ^

TypeError: Cannot assign to read only property 'response' of object '[object Object]'
    at addErrorData (/usr/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:159:16)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/broken-link-checker/node_modules/bhttp/lib/bhttp.js:567:25)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 Failed 1 broken url(s) found (889 total): 
[✗] https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12
```

I was testing out #7 and ran into this problem. I'm not sure what's wrong, I guess I'll try running it again?

**Comment by celinekurpershoek** [comment]
Are you running from version v1.0.1? I messed up some tags yesterday 😅 I'm now running the action but it can take a while since its testing the readme page with recursive urls. 

https://github.com/celinekurpershoek/link-checker/runs/1076144518?check_suite_focus=true#step:2:8

**Comment by jasikpark** [comment]
I've got v1.0.1, yes

**Comment by jasikpark** [comment]
https://github.com/jasikpark/jasik-xyz/blob/master/.github/workflows/broken-link-check.yml

```yaml
name: Broken Link Check

on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/github-actions-link-checker@v1.0.1
        with:
          # Required:
          url: "https://jasik.xyz"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveLinks: true # Check all urls on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
```
